# action.yml
name: 'Libre DevOps - Run Packer for Azure -  GitHub Action'
description: 'The heavily opinionated Libre DevOps Action to run packer, packer-compliance, tfsec and checkov, targetting Azure.'
author: "Craig Thacker <craig@craigthacker.dev>"
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  packer-path:
    description: 'The absolute path in Linux format to your packer code'
    required: true

  packer-client-id:
    description: 'The client ID for your service principal, needed to authenticate to your tenant'
    required: true

  packer-client-secret:
    description: 'The client secret for your service principal, needed to authenticate to your tenant'
    required: true

  packer-subscription-id:
    description: 'The subscription id of the subscription you wish to deploy to, needed to authenticate to your tenant'
    required: true

  packer-tenant-id:
    description: 'The tenant id of which contains subscription you wish to deploy to, needed to authenticate to your tenant'
    required: true

  packer-version:
    description: 'Which version of packer should be installed or used? Defaults to latest'
    required: true
    default: "latest"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.packer-path }}
    - ${{ inputs.packer-provider-client-id }}
    - ${{ inputs.packer-provider-client-secret }}
    - ${{ inputs.packer-provider-subscription-id }}
    - ${{ inputs.packer-provider-tenant-id }}
    - ${{ inputs.packer-version }}
